name: Heroku Deployment

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/heroku@1.0.0
      name: push to Heroku
      with:
        args: container:push -a ditado-api web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}