name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
    - uses: actions/heroku@1.0.0
      name: Login to Heroku
      run: container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

